server:
  port: 8087
#  servlet:
#    session:
#      timeout:30m # Session timeout. If a duration suffix is not specified, seconds is used. m代表分钟

spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/medical?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yang.medical.entity

